####
# 회원가입 (CREATE) 
POST http://localhost:5000/users/signup
Content-Type: application/json

{
  "nickName": "gyu",
  "email": "gee8195@naver.com",
  "password": "1234"
}

#### 
# 회원정보 조회 (READ)
GET http://localhost:5000/users/read

####
# 회원정보 수정 (UPDATE)
PATCH http://localhost:5000/users/update
Content-Type: application/json

{
  "beforeNickName": "hogu",
  "afterNickName": "gyu",
  "email": "gee8195@naver.com"
}

#### 
# 회원 탈퇴 (DELETE)
DELETE http://localhost:5000/users/delete
Content-Type: application/json

{
  "nickName": "aa",
  "email": "gee8195@naver.com"
}

#### 
# 로그인 시도 (jwt)
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "nickName": "aa",
  "email": "gee8195@naver.com",
  "password": "1234"
}